name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest #se toma la imagen preconfigurado, ahi viene el deamon de docker, por ejemplo.

    steps:
       #el primer paso es tomar todo el codigo que tengo en el repositorio
    - name: Checkout code #nombre humanamente legible para nosotros. Toma lo que tenemos en nuestro repositorio
      uses: actions/checkout@v3 # es un repositorio en github que ya viene con ciertos procedimientos para llegar a este punto
      with:
        fetch-depth: 0 #para que vaya bien adentro en la busqueda de nuestro historial de commits

        #el siguiente paso es loggearse a Docker hub
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} #son los env variables que estan en el repositorio > settings > secrets and variables > actions
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: | #que es lo que quiero correr. El | es para que cada linea sea independiente y se ejecuten una tras otra.
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION!!!!"
    
    - name: Git Semantic Version # para versionamiento automatico
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version #se necesita el id para hacer referencia a todo este paso
    
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }} # extrae el version del output del paso con id=version
      run: |
        docker build -t allanvillatorof/docker-graphql:$NEW_VERSION .
        docker build -t allanvillatorof/docker-graphql:latest .

    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push allanvillatorof/docker-graphql:$NEW_VERSION
        docker push allanvillatorof/docker-graphql:latest

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        # si no se escribe --file Dockerfile se adume que es Dockerfile por defecto